name: Sync to AWS CodeCommit

on:
  push:
    branches:
      - main # Replace with the branch you want to track

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region

    - name: Sync up to CodeCommit
      uses: tsgit18/sync-up-to-codecommit-action@master
      with:
        repository_name: resume
        aws_region: us-east-1
